name: Deploy to CloudFlare Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pages.yml'
      - 'src/**.rs'
      - 'build.rs'
      - 'input.css'
      - 'package.json'
      - 'tailwind.config.js'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2024-02-12
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2
      - uses: davidB/rust-cargo-make@v1

      - name: Pre Build
        run: |
          npm i
      - name: Build
        env:
          COLLABORATORS_API_TOKEN: ${{ secrets.COLLABORATORS_API_TOKEN }}
        run: cargo make build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./artifact --project-name=homepage
